### ISSUE TITLE
[sui-studio] help check-release executes the command

### ISSUE THREAD

**Issue by julian-gernun** [SUI-Components/sui#53]
### Package

sui-studio@4.11.0

### Description

The help command does not work as expected

### Steps to Reproduce

```
> sui-studio help check-release
```

**Expected behavior:** Information about `sui-studio check-release`

**Actual behavior:** It executes `sui-studio check-release`

**Reproduces how often:** (only for bugs) 100%

### Additional Information

I'm not man enough to execute `sui-studio help release`

**Comment by naxhh** [comment]
Hi @julian-gernun #81 provides basic help mechanisms. so new version should not perform a check/release when you provide the flag help...

Im not sure if that is enough for you since the info provided will be about sui-mono (sui-studio wraps sui-mono commands)

If not, another PR should be created for specific sui-mono help messages.

**Comment by julian-gernun** [comment]
@naxhh Yes, it's fine. My main worry was about releasing when actually just wanting some info about the command
